### ISSUE TITLE
Add map for which tiles have been "seen"

### ISSUE THREAD

**Issue by paralin** [harrischristiansen/generals-bot#4]
... to differentiate between a unseen plain tile and a seen, known to be empty, plain tile

**Comment by harrischristiansen** [comment]
The Map class now has built in memory. To check if a tile has been seen before or not, try:

TILE_EMPTY = -1
`map.grid[y][x].tile >= TILE_EMPTY`.

Tile values >= 0 are players, -1 is empty, -2 is mountain, and lower is unseen.
